name: Check Mariin Status

on:
  schedule:
    - cron: "0 0/3 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
      # - uses: djp3/puppeteer-headful@master
      
      - name: Run scripts
        run: |
          export PYPPETEER_HOME='./chromium'
          mkdir -p './chromium/local-chromium/588429/chrome-linux'
          touch './chromium/local-chromium/588429/chrome-linux/chrome'

          export MARIIN_BOT_TOKEN=${{ secrets.MARIIN_BOT_TOKEN }}
          export MARIIN_CHAT_ID=${{ secrets.MARIIN_CHAT_ID }}

          sudo pip install -r requirements.txt
          sudo python main.py
          
