# This is a basic workflow to help you get started with Actions

name: Check Marrin Status

on:
  schedule:
    - cron: "0 0/3 * * *"
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
      
      - name: Run scripts
        run: |
          pip install -r requirements.txt
          export MARIIN_BOT_TOKEN=${{ secrets.MARIIN_BOT_TOKEN }}
          python main.py
          
