name: Check Mariin Status

on:
  schedule:
    - cron: "0 0/3 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10'

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Check mariin status
        env:
          MARIIN_BOT_TOKEN: ${{ secrets.MARIIN_BOT_TOKEN }}
          MARIIN_CHAT_ID: ${{ secrets.MARIIN_CHAT_ID }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          PYPPETEER_CHROMIUM_REVISION: 1047108
        run: python main.py
          
