name: Check Mariin Status

on:
  schedule:
    - cron: "0 0/3 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
      # - uses: djp3/puppeteer-headful@master
      
      - name: Run scripts
        env:
          MARIIN_BOT_TOKEN: ${{ secrets.MARIIN_BOT_TOKEN }}
          MARIIN_CHAT_ID: ${{ secrets.MARIIN_CHAT_ID }}
          CHROMIUM_EXEC_PATH: 'chromium-browser'
        run: |
          sudo apt-get update
          sudo apt-get install -yq chromium-browser
          sudo apt-get install -y wget xvfb --no-install-recommends 
          
          pip install -r requirements.txt
          python main.py
          
