name: Check Mariin Status

on:
  schedule:
    - cron: "0 0/3 * * *"
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.2.0
        with:
          python-version: '3.10' 

      # - uses: djp3/puppeteer-headful@master
      
      - name: Run scripts
        env:
          MARIIN_BOT_TOKEN: ${{ secrets.MARIIN_BOT_TOKEN }}
          MARIIN_CHAT_ID: ${{ secrets.MARIIN_CHAT_ID }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          # CHROMIUM_EXEC_PATH: 'chromium-browser'
        run: |
          echo '[BASH INFO] !!!!!!!!!'
          echo '[BASH INFO] Install chromium'
          # sudo apt-get update
          # sudo apt-get install -yq chromium-browser

          echo '[BASH INFO] !!!!!!!!!'
          echo '[BASH INFO] Export CHROMIUM_EXEC_PATH var'
          export CHROMIUM_EXEC_PATH=$(which chromium-browser)
          
          echo '[BASH INFO] !!!!!!!!!'
          echo '[BASH INFO] Run pip'
          pip install -r requirements.txt

          echo '[BASH INFO] !!!!!!!!!'
          echo '[BASH INFO] Run script'
          which python
          which python3

          python3 main.py
          
